# $Id$

TOP=	../../..

.include "${TOP}/mk/elftoolchain.os.mk"

PROG=	ardiff

NOMAN=

WARNS?=	6

DPADD=	${LIBARCHIVE}
LDADD=	-larchive

.if ${OS_HOST} == "FreeBSD"
DPADD+=	${LIBLZMA}
LDADD+=	-llzma
.endif

.include "${TOP}/mk/elftoolchain.prog.mk"
