# $Id$
#
# TET-based test suites used by the Elftoolchain project.
#

TOP=		..

# Build TET first.
SUBDIR+=	tet

# Build tests for libraries.
SUBDIR+=	libelf
SUBDIR+=	libdwarf

# Build tests for tools.
SUBDIR+=	ar
SUBDIR+=	elfcopy
SUBDIR+=	elfdump
SUBDIR+=	nm

.include "$(TOP)/mk/elftoolchain.subdir.mk"
