# -*- mode: makefile -*-
#
# Build the programs previously extracted from the literate program
# input.
#
# $Id$

SUBDIR=

.if exists(master)
SUBDIR+=	master
.endif

.if exists(slave)
SUBDIR+=	slave
.endif

.include <bsd.subdir.mk>
