# $Id$

TOP=	../../../..

TS_SRCS=		ehdr.m4
TS_DATA=		ehdr.msb32 ehdr.lsb32 ehdr.msb64 ehdr.lsb64 \
			ehdr-malformed-1.lsb32 ehdr-malformed-1.msb32 \
			newehdr.lsb32 newehdr.msb32

.include "${TOP}/mk/elftoolchain.tet.mk"
