#
# $Id$
#

SUBDIR+=	dwarf_init
SUBDIR+=	dwarf_next_cu_header
SUBDIR+=	dwarf_get_address_size
SUBDIR+=	dwarf_siblingof
SUBDIR+=	dwarf_child
SUBDIR+=	dwarf_die_query
SUBDIR+=	dwarf_die_offset
SUBDIR+=	dwarf_die_convenience
SUBDIR+=	dwarf_attr
SUBDIR+=	dwarf_attrlist
SUBDIR+=	dwarf_form
SUBDIR+=	dwarf_loclist

.include <bsd.subdir.mk>
