.\" Copyright (c) 2011 Kai Wang
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id$
.\"
.Dd June 24, 2011
.Os
.Dt DWARF_LOCLIST 3
.Sh NAME
.Nm dwarf_loclist ,
.Nm dwarf_loclist_n
.Nd retrieve DWARF location expression list
.Sh LIBRARY
.Lb libdwarf
.Sh SYNOPSIS
.In libdwarf.h
.Ft int
.Fo dwarf_loclist
.Fa "Dwarf_Attribute at"
.Fa "Dwarf_Locdesc **llbuf"
.Fa "Dwarf_Signed *listlen"
.Fa "Dwarf_Error *error"
.Fc
.Ft int
.Fo dwarf_loclist_n
.Fa "Dwarf_Attribute at"
.Fa "Dwarf_Locdesc ***llbuf"
.Fa "Dwarf_Signed *listlen"
.Fa "Dwarf_Error *error"
.Fc
.Sh DESCRIPTION
Function
.Fn dwarf_loclist_n
retrieves a location expression list assoicated with a DWARF
attribute.
.Pp
Argument
.Ar at
should reference a valid DWARF attribute.
.Pp
Argument
.Ar llbuf
should point to a location which will hold the returned array of
pointers to the
.Vt Dwarf_Locdesc
descriptors.
.Pp
Argument
.Ar listlen
should point to a location which will be set to the number of
elements contained in the returned array.
.Pp
If argument
.Ar err
is not NULL, it will be used to store error information in case
of an error.
.Pp
Function
.Fn dwarf_loclist
is identical to
function
.Fn dwarf_loclist_n ,
except that it can only retrieve one location expression.
.Pp
Argument
.Ar llbuf
should point to a location which will hold the returned pointer
to the
.Vt Dwarf_Locdesc
descriptor.
.Pp
Argument
.Ar listlen
should point to a location which will be always set to 1.
.Pp
Function
.Fn dwarf_loclist
is deprecated for use by new application code.
.Pp
.Vt Dwarf_Locdesc
descriptors are defined in the header file
.In libdwarf.h ,
and consists of following fields:
.Pp
.Bl -tag -width ".Va ld_cents" -compact
.It Va ld_lopc
The lowest program counter address covered by the descriptor.
It is set to 0 if the descriptor is not associcated with an address
range.
.It Va ld_hipc
The highest program counter address covered by the descriptor.
It is set to 0 if the descriptor is not associcated with an address
range.
.It Va ld_cents
The number of entries returned in
.Va ld_s
field.
.It Va ld_s
Pointer to an array of
.Vt Dwarf_Loc
descriptors.
.El
.Pp
Each
.Vt Dwarf_Loc
descriptor represents one operation of a location expression.
It is defined in the header file
.In libdwarf.h ,
and consists of following fields:
.Pp
.Bl -tag -width ".Va lr_number2" -compact
.It Va lr_atom
The operator name, one of the
.Dv DW_OP_*
constants as defined in the headerf file
.In dwarf.h .
.It Va lr_number
The first operand of this operation.
.It Va lr_number2
The second operand of this operation.
.It Va lr_offset
The byte offset of this operation within the containing location
expression.
.El
.Ss Memory Management
The memory area used for the descriptor array returned in argument
.Ar llbuf
is allocated by
.Lb libdwarf .
When the descriptor array is no longer needed, application code should
use function
.Xr dwarf_dealloc 3
to free the memory area in several steps.
First, the
.Ar ld_s
field of each
.Vt Dwarf_Locdesc
descriptor should be deallocated with the allocation type
.Dv DW_DLA_LOC_BLOCK .
Then, application should free each
.Vt Dwarf_Locdesc
descriptor with the allocation type
.Dv DW_DLA_LOCDESC .
At last, the
.Va llbuf
pointer should be deallocated with the allocation type
.Dv DW_DLA_LIST .
.Sh ERRORS
These function can fail with:
.Bl -tag -width ".Bq DW_DLE_ARGUMENT"
.It Bq Er DW_DLE_ARGUMENT
One of the arguments
.Ar at ,
.Ar llbuf
or
.Ar listlen
was NULL.
.It Bq Er DW_DLE_ARGUMENT
The attribute provided by argument
.Ar at
does not contain a location expression or associate with
a location list.
.El
.Sh EXAMPLE
To retrieve the location list associated with an attribute, use:
.Bd -literal -offset indent
Dwarf_Attribute at;
Dwarf_Locdesc **llbuf;
Dwarf_Signed lcnt;
Dwarf_Loc *lr;
Dwarf_Error de;
int i;

if (dwarf_loclist_n(at, &llbuf, &lcnt, &de) != DW_DLV_OK) {
	errx(1, "dwarf_loclist_n failed: %s", dwarf_errmsg(de));
}

for (i = 0; i < lcnt; i++) {
	/* ... Use llbuf[i] ... */
	for (j = 0; (Dwarf_Half) j < llbuf[i]->ld_cents; j++) {
		lr = &llbuf[i]->ld_s[j];
		/* ... Use each Dwarf_Loc descriptor ... */
	}
	dwarf_dealloc(dbg, llbuf[i]->ld_s, DW_DLA_LOC_BLOCK);
	dwarf_dealloc(dbg, llbuf[i], DW_DLA_LOCDESC);
}
dwarf_dealloc(dbg, llbuf, DW_DLA_LIST);
.Ed
.Sh SEE ALSO
.Xr dwarf 3 ,
.Xr dwarf_dealloc 3 ,
.Xr dwarf_loclist_from_expr 3 ,
.Xr dwarf_loclist_from_expr_a 3
