.\" Copyright (c) 2011 Kai Wang
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id$
.\"
.Dd August 20, 2011
.Os
.Dt DWARF_GET_RELOCATION_INFO 3
.Sh NAME
.Nm dwarf_get_relocation_info
.Nd retrieve generated relocation arrays
.Sh LIBRARY
.Lb libdwarf
.Sh SYNOPSIS
.In libdwarf.h
.Ft int
.Fo dwarf_get_relocation_info
.Fa "Dwarf_P_Debug dbg"
.Fa "Dwarf_Signed *elf_section_index"
.Fa "Dwarf_Signed *elf_section_link"
.Fa "Dwarf_Unsigned *reloc_entry_count"
.Fa "Dwarf_Relocation_Data *reloc_buf"
.Fa "Dwarf_Error *err"
.Fc
.Sh DESCRIPTION
Function
.Fn dwarf_get_relocation_info
retrieve the next relocation array generated by the
producer instance.
This function is only applicable when DW_DLC_SYMBOLIC_RELOCATIONS flag
is set in the producer flags, and should only be called after
application code have called
.Xr dwarf_transform_to_disk_form 3 .
.Pp
Application code should call this function repeatly to retrieve all
the relocation arrays. The total number of generated relocation arrays
can be obtained by calling function
.Xr dwarf_get_relocation_info_count 3 .
.Pp
Argument
.Ar dbg
should reference a DWARF producer instance allocated using
.Xr dwarf_producer_init 3
or
.Xr dwarf_producer_init_b 3 .
.Pp
Argument
.Ar elf_section_index
should point to a location which will hold the ELF section index
of the relocation section to which the retrieved relocation array
belongs.
.Pp
Argument
.Ar elf_section_link
should point to a location which will hold the section index of
the ELF section to which the retrieved relocation array applies.
.Pp
Argument
.Ar reloc_entry_count
should point to a location which will be set to the total number
of relocation entries contained in the relocation array.
.Pp
Argument
.Ar reloc_buf
should point to a locatin which will hold a pointer to the retrieved
array of relocation entries.
.Pp
If argument
.Ar err
is not NULL, it will be used to store error information in case
of an error.
.Pp
The retrieved relocation entries are described using structure
.Vt Dwarf_Relocation_Data_s ,
as defined in the header file
.In libdwarf.h :
.Bd -literal -offset indent
typedef struct Dwarf_Relocation_Data_s {
	unsigned char drd_type;
	unsigned char drd_length;
	Dwarf_Unsigned drd_offset;
	Dwarf_Unsigned drd_symbol_index;
} *Dwarf_Relocation_Data;
.Ed
.Pp
Struct
.Vt Dwarf_Relocation_Data_s
consists of following fields:
.Bl -tag -width "Va drd_symbol_index" -compact -offset indent
.It Va drd_type
type code of the relocation entry; one of the
.Vt Dwarf_Rel_Type
enum constants.
.It Va drd_length
the size in bytes of the field to be relocated.
.It Va drd_offset
the section-relative offset of the field to be relocated.
.It Va drd_symbol_index
the symbol index associated with the relocation entry.
.El
.Ss Memory Management
The memory area used for the relocation arrays should be freed using the
function
.Fn dwarf_producer_finish .
.Sh RETURN VALUES
On success, function
.Fn dwarf_get_relocation_info
returns
.Dv DW_DLV_OK .
It returns
.Dv DW_DLV_NO_ENTRY
if there is no more relocation array to retrieve, or the flag
.Dv DW_DLC_SYMBOLIC_RELOCATIONS
is not set in the producer flags.
In case of an error, function
.Fn dwarf_get_relocation_info
returns
.Dv DW_DLV_ERROR
and set the argument
.Ar err .
.Sh ERRORS
Function
.Fn dwarf_get_relocation_info
can fail with:
.Bl -tag -width ".Bq Er DW_DLE_NO_ENTRY"
.It Bq Er DW_DLE_ARGUMENT
One of the arguments
.Ar dbg ,
.Ar elf_section_index ,
.Ar elf_section_link ,
.Ar reloc_entry_count
or
.Ar reloc_buf
was NULL.
.It Bq Er DW_DLE_NO_ENTRY
There was no more ELF relocation array to retrieve.
.It Bq Er DW_DLE_NO_ENTRY
The flag
.Dv DW_DLC_SYMBOLIC_RELOCATIONS
was not set in the producer flags.
.It Bq Er DW_DLE_NO_ENTRY
Function
.Xr dwarf_transform_to_disk_form 3
was not called before.
.El
.Sh EXAMPLES
To generate relocation entries and retrieve them, use:
.Bd -literal -offset indent
Dwarf_P_Debug dbg;
Dwarf_Relocation_Data buf;
Dwarf_Signed count, index, link;
Dwarf_Unsigned reloc_cnt, entry_cnt;
Dwarf_Error de;
int version, i, j;

/* assume dbg refers to a DWARF producer instance created
   created with DW_DLC_SYMBOLIC_RELOCATIONS flag set... */

/*
 * application code add various DWARF debugging information
 * to the producer instance...
 */

if ((count = dwarf_transform_to_disk_form(dbg, &de)) ==
    DW_DLV_NOCOUNT) {
	warnx("dwarf_transform_to_disk_form failed: %s",
	    dwarf_errmsg(-1));
	return;
}

/* ... process generated section byte streams ... */

if (dwarf_get_relocation_info_count(dbg, &reloc_cnt, &version, &de) !=
    DW_DLV_OK) {
	warnx("dwarf_get_relocation_info_count failed: %s",
	    dwarf_errmsg(-1));
	return;
}

for (i = 0; (Dwarf_Unsigned) i < reloc_cnt; i++) {
	if (dwarf_get_relocation_info(dbg, &index, &link, &entry_cnt,
	    &buf, &de) != DW_DLV_OK) {
		warnx("dwarf_get_relocation_info failed: %s",
		    dwarf_errmsg(-1));
		continue;
	}
	for (j = 0; (Dwarf_Unsigned) j < entry_cnt; j++) {
		/* ...use each reloc data in buf[j]... */
	}
}

dwarf_producer_finish(dbg, &de);
.Ed
.Sh SEE ALSO
.Xr dwarf 3 ,
.Xr dwarf_get_relocation_info_count 3 .
.Xr dwarf_reset_section_bytes 3 ,
.Xr dwarf_producer_finish 3 ,
.Xr dwarf_producer_init 3 ,
.Xr dwarf_producer_init_b 3 ,
.Xr dwarf_transform_to_disk_form 3
