# $Id$

TOP=	../../..

TS_SRCS=		ehdr.m4
TS_DATA=		ehdr.msb32 ehdr.msb64 ehdr.lsb32 ehdr.lsb64 \
			newehdr.lsb32 newehdr.msb32 newehdr.lsb64 \
			newehdr.msb64

.include "${TOP}/mk/elftoolchain.tet.mk"
