# $Id$

TOP=	../../../..

TS_SRCS=		strptr.m4
TS_DATA=		xscn-2.lsb32 xscn-2.lsb64 xscn-2.msb32 xscn-2.msb64 \
			newscn.lsb32 newscn.lsb64 newscn.msb32 newscn.msb64

.include "${TOP}/mk/elftoolchain.tet.mk"
