# $Id$

# libdwarf test suite uses libdwarf in /usr/local (i.e. SGI libdwarf),
# if TCGEN is defined.
.if defined(TCGEN)
DWARF_INC?=	/usr/local/include
DWARF_LIBS?=	/usr/local/lib
CFLAGS+=	-DTCGEN -I${DWARF_INC}
LDADD+=		-L${DWARF_LIBS}
.endif
LDADD+=		-ldwarf

DPADD+=		${LIBELF}
LDADD+=		-lelf

OS_HOST != uname -s
.if ${OS_HOST} == FreeBSD
LDADD+=		-lbsdxml
.else
LDADD+=		-lexpat
.endif

.if !defined(TCGEN)
TS_SRCS+=	${.OBJDIR}/ic_count.c
${.OBJDIR}/ic_count.c:
	${TS_ROOT}/bin/count-ic ${.OBJDIR}
CLEANFILES+=	 ${.OBJDIR}/ic_count.c
.endif

.for f in ${TS_DATA}
CLEANFILES+=	${f}.xml
.endfor

# Copy test objects(binaries) to the build directory.
.for f in ${TS_DATA}
.if !exists(${f:R})
${f}:	${TS_OBJROOT}/common/object/${f}.gz
	cp ${.ALLSRC} ${.TARGET}.gz
	gunzip ${.TARGET}.gz
.endif
.endfor

WARNS?=		2

# Test cases do not have manual pages.
NOMAN=		noman
