# $Id$

TS_SRCS=		getscn.m4
TS_DATA=		newscn.lsb32 newscn.lsb64 newscn.msb32 newscn.msb64 \
			xscn-1.lsb32 xscn-1.lsb64 xscn-1.msb32 xscn-1.msb64 \
			xscn-2.lsb32 xscn-2.lsb64 xscn-2.msb32 xscn-2.msb64

.include "../Makefile.tset"
