# $Id$

# All the test cases in this test suite need -lelftc.
DPADD+=		${LIBELFTC} ${LIBELF}
LDADD+=		-lelftc -lelf

GENERATE_TEST_SCAFFOLDING=	yes

# Test cases do not supply manual pages.
NOMAN=	noman
