#
# Libelf by Example
#
# $Id$

TOP = ..

DOC=			libelf-by-example

SRCS=			libelf-by-example.tex

IMAGES_MP=		fig-arstr.mp fig-ariter.mp fig-data.mp \
			fig-eident.mp fig-elfhdrlayout.mp fig-elflayout.mp \
			fig-filemem.mp \
			fig-phdrlayout.mp \
			fig-scn.mp fig-shdrlayout.mp fig-strtab.mp \
			fig-versions.mp 

.include "${TOP}/mk/elftoolchain.tex.mk"
